services:
  spark-master:
    image: tvrsimhan27/spark-master
    container_name: spark-master
    networks:
      - spark-network
    ports:
      - "8081:8080"
    command: ["--attach"]

  spark-worker:
    image: tvrsimhan27/spark-worker
    networks:
      - spark-network
    environment:
      MEMORY: 2G
      CORES: 1
    deploy:
      replicas: 1
    depends_on:
      - spark-master

  spark-submit:
    image: tvrsimhan27/spark-submit
    container_name: spark-submit
    networks:
      - spark-network
    ports:
      - "4040:4040"
    command: ["bash"]
    depends_on:
      - spark-master
      - spark-worker

  spark-shell:
    image: tvrsimhan27/spark-shell
    container_name: spark-shell
    networks:
      - spark-network
    depends_on:
      - spark-submit
    command: ["--attach"]

networks:
  spark-network:
    driver: bridge
