services:
  spark-base:
    build:
      context: ./spark-base
      dockerfile: Dockerfile
    image: tvrsimhan27/spark-base:${TAG}

  spark-master:
    build:
      context: ./spark-master
      dockerfile: Dockerfile
    image: tvrsimhan27/spark-master:${TAG}
    networks:
      - spark-network

  spark-worker:
    build:
      context: ./spark-worker
      dockerfile: Dockerfile
    image: tvrsimhan27/spark-worker:${TAG}
    networks:
      - spark-network

  spark-submit:
    build:
      context: ./spark-submit
      dockerfile: Dockerfile
    image: tvrsimhan27/spark-submit:${TAG}
    networks:
      - spark-network

  spark-shell:
    build:
      context: ./spark-shell
      dockerfile: Dockerfile
    image: tvrsimhan27/spark-shell:${TAG}
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge
